### ISSUE TITLE
Headless CMS - Access Token unable to access listContentModels

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#1061]
This is:
- Bug

## Expected Behavior
Using Access Token with /read API should allow me to use the `listConentModels` field.

## Actual Behavior
Throws `Not Authorized` error.

![image](https://user-images.githubusercontent.com/3920893/85414395-57a8d800-b56c-11ea-9868-93f266f57339.png)

**Comment by Fsalker** [comment]
i see two possibilities:
1. we move export const validateAccessToken to an utils package. we don't seem to have one, so we can create one. is this a good approach in our monolithic app?
2. i'll copy-paste the validateAccessToken code from api-headless-cms to api-security

**Comment by Fsalker** [comment]
more details about the bug:

this bug appears because it seems certain fields such as `listContentModels` employ different authorization. the error thrown comes from `api-security\src\SecurityError.ts` which is used in `api-security\src\hasScope.ts`.

my fix adds a new if clause doing the exact same checks we do in headless cms: `packages\api-headless-cms\src\content\plugins\index.ts`

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
