### ISSUE TITLE
Headless CMS - wrong queries generated

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#1090]
If a model was named e.g. B, then these queries are wrong:
![image](https://user-images.githubusercontent.com/5121148/86242503-200de180-bba5-11ea-8411-2c6950e65165.png)

Basically, the queries are incorrectly generated, it should be `listAs`, not `listAS`.

I checked the `pluralize` function, it's simply how it works by default. If all letters are uppercase, then the plural suffix letter will also be uppercase.

All in all, didn't have the time to check what is actually causing this error.

**Comment by EmilK15** [comment]
The steps to reproduce this problem is the following:
1. Create a Content Model with a single uppercase letter Ex. G
2. Head to the Model under Headless CMS and click on G to create a model of that
3. Click Save and Publish, this error will appear.
It's important to note here that if you use an all uppercase name like MADD (or other acronyms)
This issue does not present itself, and in the playground you will see the following:
![image](https://user-images.githubusercontent.com/9532882/87598411-2336c080-c6c1-11ea-8e58-7a57ac559379.png)
This suggests that this behavior is specific to a single uppercase letter being used as a name for a Content Model
