### ISSUE TITLE
S3 Serverless Component - must not use uppercase letters

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#1112]
Thanks to our user Arun, we discovered that having a bucket name with uppercase letter in it, will result in the whole deploy process to hang.

!["something-mine-WBy" used as a bucket name](https://user-images.githubusercontent.com/5121148/86942334-4ef7fa80-c145-11ea-9938-a7f74faa673b.png)

In the official docs, it states they state the following:
```Bucket name must not contain uppercase charactersBucket name must start with a lowercase letter or numberBucket name must be between 3 and 63 characters long```

Let's try resolving this for the upcoming release.

Thanks again Arun! 🍻 🍻

**Comment by Pavel910** [comment]
Not sure what's the best way to approach this; we could validate the `S3_BUCKET` env variable before running deploy, but the problem is that developers can use ANY env variable name instead of that one. And since bucket name is passed to several resources, we can't have a centralized place to validate this 🤔

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
