### ISSUE TITLE
Headless CMS - new environments do not show linked aliases

### ISSUE THREAD

**Issue by lauren57721** [webiny/webiny-js#1114]
## This is:

- Bug

## Specifications

  - version: 4.3.0
  - OS: Ubuntu 16.04
  - Browser: Firefox

## Expected Behavior

When you:
-  create a new environment in "Environments", 
- and then create an alias linking to the new environment in "Aliases", 
- and then go back to the "Environments" page, 

You should:
- see a message saying that the new environment is assigned to the alias.

## Actual Behavior

The message in "Environments" says "Not linked with an alias".
![aliases](https://user-images.githubusercontent.com/67826873/86975191-c88fe880-c145-11ea-93cc-991f810db10f.png)
![environments](https://user-images.githubusercontent.com/67826873/86975174-c29a0780-c145-11ea-946c-3ca1f2d238c3.png)

## Steps to Reproduce the Problem

1. From a new Webiny project, navigate to "Environments" in the Headless CMS menu.
2. Create a new environment called "Development" whose base environment is Production.
3. Navigate to "Aliases" in the Headless CMS menu.
4. Create a new alias that points to the "Development" environment.
5. Navigate back to "Environments" in the Headless CMS menu. 
6. You can see that the Development environment says "Not linked to an alias" but it should say "Assigned to: Development."

**Comment by Ashu96** [comment]
Hey, @lauren57721 thanks for reporting this issue.

This is happening because the `LIST_ENVIRONMENTS` query is not refreshing.
`packages/app-headless-cms/src/admin/views/Environments/Environments.tsx:45`

Because if you simply refresh the page you will see the update made in alias reflected in the environment itself. Obviously, this is not an ideal UX.

---
### Possible solution:
- Find out why the `LIST_ENVIRONMENTS` is not refreshing after the first initial load.
- Or we need to somehow, refresh the `LIST_ENVIRONMENTS` after `mutation` in the aliases section.
