### ISSUE TITLE
FileManager - Can't save Tags and delete Images

### ISSUE THREAD

**Issue by nkumnberlin** [webiny/webiny-js#1209]
Whenever I try to add a Tag to an image the tag won't be saved. 
Also if I try to delete an image literally nothing happens

## This is:

- Bug

## Specifications

  - version: latest Webiny build
  - OS: W10
  - Browser: Chrome, Edge, Firefox

## Expected Behavior

To add a tag for sorting, also delete Image after clicking on the bucket icon

## Steps to Reproduce the Problem

Upload a bunch of images, try to tag them or delete after uploading.

**Comment by Ashu96** [comment]
@nkumnberlin 

For image tags, Once you're happy with the edits that you have made to tags, please press `Esc` key to save them.
We already added a better, more obvious UX for this feature. 

Please try upgrading the Webiny project using yarn upgrade and then redeploy the stacks to get all new updates.

For image delete action. We'll fix this bug in the upcoming release. Thanks for reporting :+1:

**Comment by Ashu96** [comment]
The `Delete` image action is not working because the `ConfirmationDialog` has a lower `zIndex` than `OverlayLayoutWrapper`.

https://github.com/webiny/webiny-js/tree/master/packages/app-admin/src/components/FileManager/FileDetails.tsx#L146
https://github.com/webiny/webiny-js/tree/master/packages/app-admin/src/components/OverlayLayout/OverlayLayout.tsx#L11

To fix this issue, we need to add a higher `zIndex` to the `ConfirmationDialog` similar to what we have in `ImageEditorDialog` inside https://github.com/webiny/webiny-js/blob/master/packages/app-admin/src/plugins/FileManager/fileImage/EditAction.tsx#L68
