### ISSUE TITLE
CMS - Establish relations between two (or more) fields

### ISSUE THREAD

**Issue by nkumnberlin** [webiny/webiny-js#1233]
Having bigger Content Models with many fields and explicit identifiers defining parents and child references lead to more complex templates in the webiny gui,  bigger graphql queries and also more code in the frontend. 

Example:
![fr0](https://user-images.githubusercontent.com/26595416/92933681-d6fcc800-f446-11ea-8eb2-b313b71e8575.PNG)

It would be easier for the developer and the editor to add a pair of referenced fields instead of adding them one by one. This would help a lot while designing new content models.

The developer saves time, because he dosen't have to add new field in the model, query, code etc.

We would like to be able to combine multiple fields into one, which also could be duplicated (like the existing multiple input option). 
So instead of having profile picture 1, text 1, description 1;  picture 2, text 2, description 2; we would like to be able to generate object profile from the same instance. For demonstration, see the mockup below. 

Image 1:
![fr1](https://user-images.githubusercontent.com/26595416/92933495-9b61fe00-f446-11ea-85d7-6f3c0ed3ba05.PNG)
Image 2:
![fr2](https://user-images.githubusercontent.com/26595416/92933510-a1f07580-f446-11ea-8732-257fb763ed68.png)

## This is:

- Feature request

**Comment by doitadrian** [comment]
Sorry for the delay @nkumnberlin.

I believe I understand what you need.

So instead of adding profile image 1, profile image 2, profile image 3, via the single files field, and then doing the same with title and description via text fields, you would want to have a field that consists of multiple entries, and where a single entry is all that - so a profile image, description, and text. Right?

If I was right there, well, unfortunately, this can't be achieved at the moment - out of the box.

But it can be achieved by a custom field, which you can write your self, using plugins. Would that be helpful to you?

I think we received several questions related to custom fields, so I might just write an article on our docs page while I'm at it.
