### ISSUE TITLE
webiny:admin build failes during deployment

### ISSUE THREAD

**Issue by jcode-hub** [webiny/webiny-js#1249]
## This is:

- Bug

## Specifications

  - version: 4.12
  - OS: Ubuntu 20.04

## Expected Behavior

The build of the admin app should be successfull

## Actual Behavior

I tried to update my existing project with `yarn upgrade` and then run `yarn webiny deploy apps --env=prod` again and the build failed (no problems with api though)
Then I created a new project to check if this is a problem with my cd pipeline and got the same error there:
```
This is the first deploy of prod environment, so it may take a few minutes.
  💡 Loaded prod environment from <projectRoot>/.env.json.

  ✔ Great! Your MongoDB is accessible.

  webiny Collecting components from the template. +0ms
  webiny Executing the template's components graph. +33ms
  webiny:lambdaRole Creating role 'b01ee561_upgradetest_apps_prod_lambdaRole'. +0ms
  webiny:lambdaRole Role 'b01ee561_upgradetest_apps_prod_lambdaRole' was successfully deployed to region 'eu-central-1'. +21sng...
  webiny:admin Building 'admin' +0ms
  error Command failed with exit code 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
## Steps to Reproduce the Problem

1. `npx create-webiny-project upgradetest --template=cms`
2. `yarn webiny deploy api --env=prod`
3. `yarn webiny deploy apps --env=prod`

**Comment by doitadrian** [comment]
Will take a look now @jcode-hub.

**Comment by latotty** [comment]
@doitadrian Checked on my admin, and it relates to https://github.com/webiny/webiny-js/issues/1247

**Comment by doitadrian** [comment]
I see, I can see this in my `yarn start`, in a brand new project:

![image](https://user-images.githubusercontent.com/5121148/93436763-7dbfe900-f8cb-11ea-88c7-52e4c7f0b2fb.png)
(which is what is shown in #1247 - thanks @latotty )

At first, this looks to me like some 3rd party dependency got changed. Because this is a brand new issue, and I'm pretty sure nothing has changed in this department.

Let me take a look deeper into what we can do about it.

**Comment by TommyJackson85** [comment]
@doitadrian thanks! I'm getting the error too. At first I thaught it was related to my own changes but when I pulled the master branch to update it, the error came up then.

**Comment by doitadrian** [comment]
[4.12.1 release in progress.](https://github.com/webiny/webiny-js/actions/runs/259056644)

**Comment by doitadrian** [comment]
The 4.12.1 is up, please give it a try (I tried it already on my own machine).

Thanks @TommyJackson85 @latotty @jcode-hub!

**Comment by latotty** [comment]
@doitadrian thanks, working for me also 👍 

BTW: the pipeline's "Deploy Apps stack" step fails https://github.com/webiny/webiny-js/runs/1127692810?check_suite_focus=true

**Comment by jcode-hub** [comment]
I can also confirm the fix worked! Nice, many thanks @doitadrian  and the team!

**Comment by doitadrian** [comment]
Nice guys! 🎉 

BTW @latotty, yeah, saw that one, which immediately got me concerned that something went wrong again, and that's why I immediately tried the new version locally.

Not sure why it failed, especially because while releasing `4.12.1.beta.0`, everything was OK.

Will have to debug this one.

**Comment by TommyJackson85** [comment]
Great work! Thanks! It's up and running for me again!
