### ISSUE TITLE
docker-compose deployment

### ISSUE THREAD

**Issue by vmelnych** [webiny/webiny-js#1377]
## General:
Would be great to increase the onboarding ratio by reducing complexities for non-React community and providing a friendly docker-compose file with the containerized environment. Otherwise, a good deal of possible followers and evangelists will fall off due to NodeJS module dependencies (node, npm, yarn) nightmares. For me launching `Strapi`, `Squidex` and `Directus` was a lot easier, which means they get more popular for fewer complexities. 
Second issue - the AWS dependency limits the product's future.

## This is a:
- Feature request

## Specifications
  - OS: `Windows 10` + `WSL2` (`Ubuntu`) + `Docker`
  - Browser: `Chrome`/`Firefox`

## Expected Behavior
The user clones the repo, runs `make install` (pulls from docker hub) modifies `.env`, runs `docker-compose up -d` and enjoys using the app. No project building/compiling is expected.

## Actual Behavior
I cloned the repo, read the lengthy manual full of specific terminology and insufficient clarity of the right sequence of steps. Then after having installed a proper `yarn` (there are two yarn notions apparently and the other one comes with cmdtest package) the user will struggle to compile projects. I had to troubleshoot different versions of npm, yarn, node, packages, installations, updates, incompatibilities and finally after having started `api`, `site app` and `admin app`, could not enjoy anything, as I have got a few unresolvable errors (I suspect that some outdated module did not properly read my `.env` and `.env.json` files). Finally, after 3 days struggling with Webiny I had to give up.

**Comment by Pavel910** [comment]
Hi @vmelnych, thanks for letting us know about your problems.  Sorry you ran into those, but you should've ask for help on our community Slack, we're there each and every day, we'd help you out. The problems you're describing are not something anybody reported to us before and we have over 500 community members who tried Webiny + there are several companies using Webiny in production.

We're aware of not-so-friendly experience with v4 (due to Mongo and deploy process), and it's been taken care of in the upcoming v5, which is currently in `beta`.
However, it doesn't mean that we've turned to docker. We haven't and we don't plan to. Our views are explained in this here article: https://www.webiny.com/blog/local-development-is-dying-and-it-s-for-the-better

Webiny is a product that is developed for the cloud and serverless. We don't aim at attracting each and every developer, only those interested in serverless technologies and cloud infrastructurte. Thus, Strapi and other local-based systems are not our competitors, they have their own target audience, we have ours.

v5 beta will be officially released in a couple of days, there are many major changes coming, so if you're interested in trying it out, join our Slack community at https://www.webiny.com/slack and you'll see the announcement once we publish it.

Cheers!
