### ISSUE TITLE
FEATURE: Provide simple way to make arbitrary changes to PB site metadata schema

### ISSUE THREAD

**Issue by jimjoes** [webiny/webiny-js#1427]
## This is:
- Feature request

## Detailed Description
It would be useful to have a simple way to add/modify fields in the page builder site settings. For example, add support for arbitrary social profiles, or add metadata (for example address) that can be added to queries used for footer/header etc.

It makes more sense for site metadata to live in the website settings, rather than to add *another* menu item, which is what I think you'd get if you registered an additional plugin?

**Comment by Pavel910** [comment]
@econtentmaps this will soon be possible. In my current PR #1692 I introduced a `ViewPlugin` and using that you'll be able to hook into views that allow extension. In our apps, we'll be adding "regions", like this:

```tsx
<View name={"admin.settings.pageBuilder.website.main"}>
    {* View content goes here *}
</View>
```

And then you'll be able to add your own stuff like so:

```tsx
    new ViewPlugin({
        name: "admin.settings.pageBuilder.website.main",
        render({ children }) {
            return <Fragment>{children} and whatever else you want</Fragment>;
        }
    })
```
With that, you'll be able to completely replace the region r add stuff before/after the original content.

There will be docs later on (because you'll also need to expand the GraphQL schema using plugins, etc.), but the groundwork for this is done and will be available in `5.9`.

**Comment by Pavel910** [comment]
This is still awaiting proper solution. We want to reimplement the `website` settings view using UI Composer, then this will become easy and dev-friendly.

**Comment by Pavel910** [comment]
This is already implemented using a new React-based plugin. I'm hoping to document this in the upcoming week, because another user asked about this same thing.
