### ISSUE TITLE
Content entry ownership checking not coherent

### ISSUE THREAD

**Issue by taifok** [webiny/webiny-js#1675]
## This is:

- Bug

## Specifications

  - version: 5.6.0

## Detailed Description

The ownership checking in some functions is checked by `createdBy`, but some is checked by `ownedby`.

https://github.com/webiny/webiny-js/blob/b6a555663c4cfd3c1e6213b616b1decbd048caa0/packages/api-headless-cms/src/content/plugins/crud/contentEntry.crud.ts#L172

this is checked by the default param, which is `createdBy`. in `getByIds`

https://github.com/webiny/webiny-js/blob/b6a555663c4cfd3c1e6213b616b1decbd048caa0/packages/api-headless-cms/src/content/plugins/crud/contentEntry.crud.ts#L564

Now I just wrote a plugin to override the `getByIds` function in `context.cms.entries`.

**Comment by Pavel910** [comment]
@taifok it's not a bug. There's a difference between `createdBy` and `ownedBy`. 
`Owner` of the entry is the person who created the first revision of that entry.
But other people can create new revisions, in which case their ID is stored in `createdBy`, but `ownedBy` is still the original user.

Then, based on permissions, you can do some actions depending of you `own` the entry.

Is there a scenario where you found permissions or data not applied as it should be?

**Comment by Pavel910** [comment]
@doitadrian @Ashu96 maybe you can give this a second look to see if this _is_, in fact, a bug?

**Comment by Pavel910** [comment]
@taifok checked this internally. The line may look confusing if you don't dig into the code:

```ts
utils.checkOwnership(context, permission, originalEntryRevision, "ownedBy");
```

This means the following:
_Check the permission, and if it only allows `own` records to be modified, but you're not the owner, throw an error._

The `ownedBy` here means:
_Use `originalEntryRevision` and check its `ownedBy` field to compare its value against the current user_.

If the permission allows the user to perform actions on _all_ records, then everything is ok.

So to confirm - it's not a bug. Different operations have different logic, and thus will use different fields to check for permissions.

For example, `getByIds` is using `createdBy`, because that will contain your user's ID even if you're not the owner of the entire entry, but you _are_ the author of that revision, so it's ok for you to see it.

**Comment by taifok** [comment]
@Pavel910 Thank you for your reply.

But there is still something I don't understand.

Below is the code snippet of `getLatestByIds` in v5.7.0
https://github.com/webiny/webiny-js/blob/6dad37f82fae24da575e3ce662327e7f91e43d2b/packages/api-headless-cms/src/content/plugins/crud/contentEntry.crud.ts#L149-L162

When another user created the latest revision, the `owner` of the entry will not get the entry since it is only checked by `createdBy` but not `ownedBy`.

Shouldn't the permission be checked by `createdBy` or `ownedBy`? It passes if the identity match one of them.

**Comment by Pavel910** [comment]
@taifok if the owner of the entry has the permission specified like this (see below), then he'll still get all revisions back, no matter what field we're checking, because [we skip the check if you are allowed to see everything](https://github.com/webiny/webiny-js/blob/6dad37f82fae24da575e3ce662327e7f91e43d2b/packages/api-headless-cms/src/utils.ts#L185):
![image](https://user-images.githubusercontent.com/3920893/120807442-3c9a6280-c548-11eb-98d2-74e0a9188b7d.png)

However, your question got me thinking and I think you're right that there _is_ a bug, if the owner of the record can only see _his own records_ (the permissions would look like this):

![image](https://user-images.githubusercontent.com/3920893/120807658-7a978680-c548-11eb-8a24-8fed3d739f24.png)

In this case, if another user creates a revision, the owner will not be able to see that revision, because, as you pointed out, we're only checking the `createdBy` field.

Great catch, and I think it's far easier to check for both fields, as you suggested, than thinking which field to check.
