### ISSUE TITLE
Form Builder "Pattern" type validators missing from UI

### ISSUE THREAD

**Issue by Quakefury** [webiny/webiny-js#1706]
## This is:

- Bug

## Specifications

  - version: 5.8.0
  - OS: MacOS
  - Browser: both Safari and Chrome

## Expected Behavior
As a user when i enter the form builder application, and create or edit a field into the form and edit the validators i expect to see a "pattern" validator section.

## Actual Behavior
As a user when i enter the form builder application, and create or edit a field into the form and edit the validators i do not see a "pattern" validator section. Even tho i can see it in the headlessCMS application.

## Steps to Reproduce the Problem

1. Enter FormBuilder Application in the Webiny Admin
2. Create or Edit new form
3. Drag a new field into the form
4. Edit the field setting
5. Select Validators tab

## Possible Solution

<img width="1618" alt="Screenshot 2021-06-09 at 14 02 42" src="https://user-images.githubusercontent.com/12550709/121353032-b8702280-c92d-11eb-8f25-ea2e020e817d.png">

**Comment by karthick3018** [comment]
@Pavel910  I'd love to work on this if assigned

**Comment by Pavel910** [comment]
@karthick3018 sure, go ahead! To give you some context: most likely we messed up plugin names/types during a refactor, so that's where I would start. All form editor validators live here: https://github.com/webiny/webiny-js/tree/next/packages/app-form-builder/src/admin/plugins/editor/formFieldValidators

And this is where you'll find the `Validators` tab shown in the screenshot above:
https://github.com/webiny/webiny-js/blob/next/packages/app-form-builder/src/admin/components/FormEditor/Tabs/EditTab/EditFieldDialog/ValidatorsTab.tsx
