### ISSUE TITLE
User passwords are stored as plain-text in dynamodb

### ISSUE THREAD

**Issue by cemreinanc** [webiny/webiny-js#1841]
## This is:

- Security Issue

## Expected Behavior

As webiny uses aws cognito as identity provider, I assume it doesn't need to store user passwords at all? If there is a need to store it in dynamodb, at least it needs to be hashed with some decent algorithm like bcrypt.

## Actual Behavior

Passwords are accessible in plain text in dynamodb at "U#{email}" keys. 

## Additional Info
- I didn't check but also elasticsearch data could possibly contain these plain text passwords. It needs to be checked while fixing.
- This fix should also contain the logic for deleting old plain text password data from both dynamodb, elasticsearch and possible cache locations.

**Comment by Pavel910** [comment]
@cemreinanc We don't store any data in ES for users, so no worries.
This is a bug we discovered as well the other day, it was introduced when we added `UserPlugin` class.
Since Cognito is attached to the system using that plugin, it needs the password to be able to create a new admin user using Cognito Admin SDK. What happened is - password was not _unset_ from the input, and so ended up in Dynamo.

We never store passwords, plain text or encrypted. That part is entirely on IdP, but this is an unlucky miss.

The fix will be a part of 5.12. release. Thanks for reporting, as this is an important one!

**Comment by Pavel910** [comment]
@cemreinanc Since 5.12. may not land on Monday, I'll release a patch version with an upgrade to cleanup DynamoDB table during the day so the affected users can sort this out ASAP.

**Comment by cemreinanc** [comment]
Hey thanks for quick response and resolution.  

I'm not using it in production yet so while i can wait for 5.12 i also think it will be the best to release a patch asap for the production users since its critical. 🙏🏻

**Comment by Pavel910** [comment]
@cemreinanc Fix is released: https://www.webiny.com/docs/changelog/5.11.1
