### ISSUE TITLE
Validations are not working on webiny Checkbox and Radio Button

### ISSUE THREAD

**Issue by anishlp7** [webiny/webiny-js#1844]
## Specifications
* version: Webiny 5.11.0
* OS: Windows 10
* Browser: Chrome

## Expected Behavior
My Expected Behaviour is when i click the submit button, the validators need to check whether the data are not empty when the required field is checked. Hence the form shouldn't get submitted.

## Actual Behavior
I'm having a survey form with radio buttons and check-boxes. I have added validations on every radio and checkboxes since when i click the submit button, the validations are not working for the radio button and checkboxes. The Survey data's are submitted with empty fields.

**Comment by Pavel910** [comment]
@anishlp7 is this Form Builder you're talking about?

**Comment by anishlp7** [comment]
@Pavel910 Yes.. Creating Forms using formbuilder, validations works on the input text fields but not on the radio button and checkboxes. If i click the submit button it doesn't checking the validations, the data are passed and stored.

**Comment by sunnythelucky** [comment]
I am having the same issue. Was it solved?

**Comment by Pavel910** [comment]
@sunnythelucky unfortunately not. This is still an issue.

**Comment by Pavel910** [comment]
Adding more context to this issue:
- radio buttons get a default value of `[]` assigned, which is weird; should be `undefined`
- checkboxes only have a `required` validator available. It is necessary to have a `minLength`, to be able to require  certain number of values. The `required` validator is not working because the default checkbox value is `[]`, and it effectively _is_ a valid value, so `required` on its own is not enough to make the field invalid, without having a `minLength` as well.

![image](https://user-images.githubusercontent.com/3920893/161100254-80f651ed-8a9f-40b9-b868-a5458aa3a623.png)
