### ISSUE TITLE
RequireNewPassword component doesn't include all fields in payload send to Cognito

### ISSUE THREAD

**Issue by jimjoes** [webiny/webiny-js#1968]
### Version
5.15

### Operating System
MacOS 11.6

### Browser
Chrome 94.0.4606.81

### What steps will reproduce the bug?
1. Fork and clone repo
1. yarn
1. setup project
1. deploy api
1. start admin app
1. In my case, loading the admin app asks for a password (I think it should ask to setup the installation).
1. Create a new user in Cognito
1. Log in with new user temporary password
1. Enter required fields in requireNewPassword form
1. On form submit, the Cognito call doesn't include the given name and family name fields even though they're present in the form.

![image](https://user-images.githubusercontent.com/61049336/137599832-38faf693-afbf-4c23-a51c-815d6239a381.png)

NEW_PASSWORD and USERNAME are included in the payload, but GIVEN_NAME and FAMILY_NAME aren't.

See 

### What is the expected behavior?
It sends the correct details and the user can log in

**Comment by Pavel910** [comment]
@econtentmaps ~what was the scenario in which it prompted you to enter those 2 fields? Did you by any chance created a new user directly in the Cognito User Pool console, and tried logging in with that user, or was this a password reset for your regular admin user created via the admin app?~

Re-read your steps to reproduce again. Step 6. is odd, if it's a fresh deployment it should walk you through the installation wizard. Try removing your localStorage data since all admin apps start on `localhost:3001` so local storage is shared on that same domain, and it should start the installation process.

Step 7. answers my original (scratched) question. Looks like a bug.

**Comment by jimjoes** [comment]
This was a user created via Cognito directly, yes.

The admin setup package didn’t run, so I set up a user in Cognito as a diagnostic step.

The ‘bug’ is just that the component isn’t sending the data the form knows to ask for. I imagine it’s an edge case, however as this wasn’t a correctly configured system, that user journey is unlikely to be needed. Still, thought I’d raise it as a tidying up exercise.
