### ISSUE TITLE
Finish new Page Builder Button / Action Settings

### ISSUE THREAD

**Issue by adrians5j** [webiny/webiny-js#2052]
> This issue is a continuation of https://github.com/webiny/webiny-js/pull/2022, which wasn't released with `5.18.0` due to a couple of polishes that still need to be done.
 
Hey @econtentmaps ,

here are a couple of things we'll just need to take a look at before making the new feature official.

1. The most important issue is the fact that on new projects, in the button settings, we cannot see both previous Link nor the new Action settings. This is related to the fact that the new action plugins is not registered, I believe [here](https://github.com/webiny/webiny-js/blob/next/packages/app-page-builder/src/editor/plugins/elementSettings/index.ts#L31).

![image](https://user-images.githubusercontent.com/5121148/143456146-4d71a1fd-9eb3-48f3-9f4f-246e6613c9d6.png)

BTW, it's interesting though that we've added a change [here](https://github.com/webiny/webiny-js/pull/2022/files#diff-bc7fbf9c46443f4ced176c031a3318e81da39ebb042ab4337dc8bfd55276dd6a), but yeah, that plugin doesn't really exist because it was not included in the first file.

2. The 2nd, a bit trickier, problem is:  what happens to projects that used the Link settings for button?

We cannot just remove the `pb-editor-page-element-style-settings-link` plugin, and introduce `pb-editor-page-element-style-settings-action`. Because in the database, if the `pb-editor-page-element-style-settings-link` was used, settings would no longer be correctly shown in the editor.

Ultimately, I think that, for backwards compatibility purposes, we'll need to stick with the `pb-editor-page-element-style-settings-link` as the name of the settings.

3. When an action doesn't require any params, the label "None Required" is not in style with the rest of the UI. Let's see if we can use the `Typography` component so that's looking a bit nicer.

4. The input that's used for selecting the action / callback is larger then others. Let's try and make it smaller, e.g.:
![image](https://user-images.githubusercontent.com/5121148/143459553-ef7c55d4-a5a3-40f2-8211-2df7c25c2708.png)

**Comment by jimjoes** [comment]
Hi,

I don't fully understand the issue in point 2... aside from the objects stored in the page structure for a button by the settings component (i.e. the newer `action` key and original `link` key along with the other, unchanged ones) what data is stored for the button? Is there plugin name stored as well?

**Comment by jimjoes** [comment]
Hi. I've tested the backwards compatibility as requested and the settings component reads and saves the data correctly, for both old style buttons and new. Tested by forking 18.3, creating a page with a couple of buttons, then removing link and adding action as plugins for button (note the link plugin remains as it's used by image and a few other components). I did however find a problem with the render component's handling of old buttons. If you *modify* an old button, the modified data is saved correctly into the action key, but the render component needed an additional logic check - if there is a link key AND no action key, then use the values from link, otherwise use the values from action. Originally it was just checking for the presence of the link key, which would always be the "old" data, even after the user changed it using the new action control.

**Comment by jimjoes** [comment]
Regarding point 4. Originally the callback/handler field used the select component, which is styled consistently with the other inputs, but you asked me to change it to autocorrect, which is styled like that (i.e. much bigger). I've had a look at the docs and the base type, but there doesn't appear to be any baked in style options for Autocorrect fields, so unless I do some custom styling, I guess that's what it *should* look like for consistency with all the other autocorrect fields in use across the admin UI.

**Comment by jimjoes** [comment]
@doitadrian

**Comment by adrians5j** [comment]
Not relevant anymore.
