### ISSUE TITLE
Backward pagination support

### ISSUE THREAD

**Issue by hariharasudhan-nineleaps** [webiny/webiny-js#2281]
Right now webiny supports forward pagination in graphql, but we have use case where we need to implement backward pagination, as users will scroll up to view old items or click prev button from website to see old page. In webiny graphql schema has `next` key only where we can forward through items, we need to add `prev/before` attribute to support backard pagination.

**Comment by brunozoric** [comment]
Hi @hariharasudhan-nineleaps 
You can implement that in the UI part of your application by storing previous cursor. If you want previous cursors to be there after the UI reload, maybe store them in the local cache.
Unfortunately, for us it is generally impossible to track which page is previous one without querying a lot of data.
Why?
Let's say you have 1000 items and you paginate by a 100.
First cursor would be "abc", second one "yxz", third one "axb". When we get to the third cursor, we do not know what is the first one without querying the data. In case of DDB only deployment, yes, it is possible because cursor is an encoded number of item from which to start the data output.
In case of DDB+Elasticsearch deployment we would need to query the data, in reverse order, starting from the current cursor to find which is the previous one. That is not acceptable from the performance side for us.
