### ISSUE TITLE
admin ui fails to notice model changes

### ISSUE THREAD

**Issue by snstanton** [webiny/webiny-js#2286]
### Version

5.24.0

### Operating System

MacOS

### Browser

Firefox

### What steps will reproduce the bug?

Create two models with the following fields

ModelA:
```{
            id: "type",
            fieldId: "type",
            label: "Type",
            helpText: "Session, Post, or Video",
            type: "text",
            predefinedValues: {
                enabled: true,
                values: [
                    { label: "Session", value: "Session" },
                    { label: "Post", value: "Post" },
                    { label: "Video", value: "Video" }
                ]
            },
            validation: [required],
            renderer: { name: "select-box" }
        },
```

modelB:
```
     {
            id: "type",
            fieldId: "type",
            label: "Type",
            helpText: "This is used to select the icon for the file.",
            placeholderText: "Slides, PDF, or Link",
            type: "text",
            predefinedValues: {
                enabled: true,
                values: [
                    { label: "PDF", value: "PDF" },
                    { label: "Slides", value: "Slides" },
                    { label: "Link", value: "Link" }
                ]
            },
            renderer: { name: "radio-buttons" }
        },
```

* Save and publish an entry for model b.
* View the saved entry
* Select ModelA and create a new entry

Note that the Type field is still showing the radio-button renderer and values from Model B

### What is the expected behavior?

When switching from ModelB to ModelA, the Type field should be updated to reflect the corresponding renderer and predefined values.

### What do you see instead?

The schema/values from ModelB are displayed when creating a new ModelA instance if you switch directly from B to A.

### Additional information

This appears to be a data flow issue when the component is updated in place.  If you visit ModelA first, then you see the correct values.

**Comment by brunozoric** [comment]
Hi @snstanton 
The issue is in the `id` property of the fields, they cannot be the same. ApolloClient has some crazy magic cache that takes those values and caches by them and when returning the data, it inserts the last fetched model field.
We could possibly check all the field `id` values each request, but I think thats a waste of time to do every time :confused: I will add comment about uniqueness into the code.e

**Comment by Pavel910** [comment]
Just to expand a little bit on that answer, the `id` field is generated automatically when you're using the model editor via the UI. But since you're creating the content models via code, you need to make those `id` properties unique yourself. You could just make them be like `{modelId}{uppercaseFirst(id)}`, so for example: `id: "bookType"`.
