### ISSUE TITLE
Form Builder - limited number of form fields

### ISSUE THREAD

**Issue by mislavstreicher** [webiny/webiny-js#2293]
### Version

5.24.0

### Operating System

MacOS 12.2.1

### Browser

Chrome

### What steps will reproduce the bug?

Create a new form using Form Builder and add more than 10 fields to the form. 

### What is the expected behavior?

When published, the form should look exactly like in the preview. Or you should get a notification about the set limit on the number of fields. 

### What do you see instead?

I've created a form with more than 10 fields and "successfully" published it without any warnings. 
When you open the preview of the published form, it will only feature the first 10 fields followed by a SUBMIT button. And all other fields after the 10th have been deleted without warning.

**Comment by Pavel910** [comment]
@mislavstreicher I created a form with 12 fields, and all 12 fields are rendered successfully on the website.
It would be super useful to see your form configuration, because there are no limitations on the number of fields you can add to the form that we know of.

![image](https://user-images.githubusercontent.com/3920893/160452474-0d97c9db-2395-4d06-82c2-3ff18da9e7bc.png)

**Comment by m0nikaza** [comment]
fixed already
