### ISSUE TITLE
fm-manage-s3-lambda-permission allows accessing from all AWS accounts

### ISSUE THREAD

**Issue by madwyn** [webiny/webiny-js#2298]
### Version

5.24.0

### Operating System

SUSE Linux

### Browser

Firefox

### What steps will reproduce the bug?

After installation, a policy statement was created with the following content:

```json
{
 "ArnLike": {
  "AWS:SourceArn": "arn:aws:s3:::fm-bucket-eda8ba3"
 }
}
```

### What is the expected behavior?

The policy should limit the access only from the existing account or allowed accounts, for example:

```json
{
 "StringEquals": {
  "AWS:SourceAccount": "666660006660"
 },
 "ArnLike": {
  "AWS:SourceArn": "arn:aws:s3:::fm-bucket-eda8ba3"
 }
}
```

### Possible solution

Add a restriction to the current account.

**Comment by kedrzu** [comment]
Hi @madwyn, thanks for bringing this issue to our attention.

If I understand correctly, a security issue may occur only if there is an S3 bucket with the same exact ARN on some other AWS account. Since S3 bucket names (and thus ARNs) are globally unique, the only case I can think of is when you delete your bucket and someone else creates a new one with the same exact name, and only then lambda would respond to S3 events from some other account's bucket.

However, still, it can be considered a vulnerability, so we will tackle this in the next sprint probably.

For now, you can tweak your pulumi configuration here: https://github.com/webiny/webiny-js/blob/next/api/pulumi/prod/fileManager.ts#L141
You can retrieve AWS account ID same as here: https://github.com/webiny/webiny-js/blob/next/api/pulumi/prod/policies.ts

**Comment by madwyn** [comment]
Hi @kedrzu, thanks for looking into this.

Yes, it's not about the logic and the way the function itself works. It's about the policy itself.

Our organisation has strict security policies (SCP) applied to all AWS accounts, I received a severe ticket during midnight caused by this world accessible policy.

I would assume in other organisations they may have the same policy enforced.

Thank you for considering improving it in next sprint, I certainly would welcome an upstream change.

I will also take a look of the link you provided. I'm still learning the basics of webiny, thanks for your great work making it happen.

**Comment by madwyn** [comment]
I installed the latest version two weeks ago and this issue still persisted.

I know how to fix this manually, but are there any plans to have it fixed in this repo?

**Comment by Pavel910** [comment]
@madwyn we're working on makin all buckets private for the next release, and I'll have a look at this issue as well.

**Comment by Pavel910** [comment]
@madwyn if your project was created with Webiny >= 5.29., you'll get a fix for this in our next release.
If there are any other resources that are causing troubles for you, please let us know.

![CleanShot 2022-08-01 at 12 20 39](https://user-images.githubusercontent.com/3920893/182128252-1d17b79f-44f6-4c7d-98b2-b0e1fc1b97ea.png)

**Comment by madwyn** [comment]
Thanks for resolving this.
