### ISSUE TITLE
Users name not updated in Page Builder Created By field

### ISSUE THREAD

**Issue by plsalvado** [webiny/webiny-js#2359]
### Version

5.25.0

### Operating System

macOS

### Browser

Safari

### What steps will reproduce the bug?

1. Create a new page in PB
2. Change the user's first name and last name in Account Details
3. Go back to PB and you will see that the "Created by" description still references the old name

### What is the expected behavior?

The Created By description should always reflect the latest first/last name of the user.

### What do you see instead?

The "Created by" description still references the old first/last name, even if the name has changed in the meatime.

<img width="706" alt="image" src="https://user-images.githubusercontent.com/8825508/165518099-a5752c53-b9b8-4ffe-a922-a6e31e7a0637.png">

**Comment by Pavel910** [comment]
Due to data denormalization (NoSQL), this is one thing that is not going to be updated. `createdBy` is not stored as a reference, but as exact values, to avoid unnecessary data reads (and paying for it). Keep in mind (remember Okta integration?) that a system might not have records about users, so the data is taken from identity token and stored right there in the record. If a user changes his name in Okta, that's outside of our reach.

It's a trade-off, but not a crucial one. 

If anybody actually finds this to be a deal breaker, they can implement a workaround themselves (we can provide instructions). But that comes at a cost of reading the DB all the time, when most of the time user information doesn't change, but you're still paying for reads.
