### ISSUE TITLE
More Flexibility on Models Created Using Admin Scaffold

### ISSUE THREAD

**Issue by chanesteves** [webiny/webiny-js#2604]
### Is your feature request related to a problem? Please describe.

Currently, when you [extend admin area](https://www.webiny.com/docs/admin-area/new-app-tutorial/scaffolding), the related GraphQL queries that can be called to retrieve the records of models (e.g. ToDo) created via API are limited to:

- retrieving a record by ID (e.g. getToDo)
- retrieving all records (e.g. listToDos)

![Screenshot 2022-09-05 221920](https://user-images.githubusercontent.com/5785059/188472970-4663050d-ce9f-45ca-b324-b1f0e11386a3.jpg)

### Describe the feature's behavior.

Ideally, we should be able to filter these GraphQL API retrievals by specific field(s) (e.g. title) by adding queries with _where_ parameters.

### Describe alternatives you've considered.

N/A

**Comment by Pavel910** [comment]
Scaffolds are there just to give you a starting point. Since DynamoDB querying is very different from relational databases, your querying/filtering very much depends on the data model; and vice versa; your data model and indexes depend on what access patterns you need.

These are not meant to give you ready-made apps, but rather give you a skeleton which you then upgrade to fit your project needs.

That said, we don't plan to make these scaffolds any more elaborate than what they currently are. On the other hand, scaffolds are just plugins to the CLI, so you can create your own scaffolds to satisfy your day-to-day development workflows and project requirements. For examples, have a look at this plugin: https://github.com/webiny/webiny-js/tree/next/packages/cli-plugin-scaffold-admin-app-module
