### ISSUE TITLE
website-router-origin-request resource does not respect resource name configuration

### ISSUE THREAD

**Issue by timruppert** [webiny/webiny-js#2637]
### Version

5.32.0

### Operating System

Mac 12.3.1

### Browser

N/A

### What are the steps to reproduce this bug?

To configure our resources, we added this snippet of code to make them easily identifiable in our apps/*/webiny.application.ts files:

```
        app.onResource(resource => {
            // When set directly, you get unique ID appended by Pulumi.
            resource.name = `${stage}-${resource.name}`;
        });
```

### What is the expected behavior?

As with all of our other resources, I would expect the name to change to {prefix}-website-router-origin-request 

### What do you see instead?

It remains with it's original name of something like website-router-origin-request-generatedID

**Comment by Pavel910** [comment]
@timruppert Looked into this, it's because of direct instantiation of a Pulumi resource, instead of using `app.addResource`, which then executes your hooks.

![CleanShot 2022-10-20 at 08 53 21@2x](https://user-images.githubusercontent.com/3920893/196877228-95c80b57-f491-4a66-9af5-2447bbc988ca.png)

It's an easy fix, we'll probably get it into the next release.

**Comment by timruppert** [comment]
That's fantastic @Pavel910 - thank you.

**Comment by Pavel910** [comment]
@timruppert this is fixed and released! 
See: https://www.webiny.com/docs/release-notes/5.33.4/changelog#introduced-prefixed-cloud-infrastructure-pulumi-resource-names-2858
