### ISSUE TITLE
Terraform implementation

### ISSUE THREAD

**Issue by JamesMillerBlog** [webiny/webiny-js#2702]
### Is your feature request related to a problem? Please describe.

Hi there, quick question - does Webiny have a terraform implementation that I can use?

### Describe the feature's behavior.

My ideal scenario is to use HCL to create the Webiny CMS.

### Describe alternatives you've considered.

I've looked at Pulumi, it does look really cool and I'd love to learn it sometime.

Learning Pulumi makes my use of this CMS more of a long-term investment.

In the meantime I'd love to use this CMS if at all possible with a technology I'm already familiar with.

If there was a Terraform implementation - this would be super helpful and I would love to use this, please let me know!

**Comment by Pavel910** [comment]
@JamesMillerBlog sorry for a late reply, I hope you managed to get a response on our Community Slack, but if not, here it is: 
Pulumi is our favorite tool because it allows us to use it programmatically. We've built a layer on top of it which allows customization via code, and that allows us to ship the default config, with tons of resources preconfigured, and let users modify those resource, and add their own, via code. 

By not exposing infrastructure definition directly in the user's project (like we had prior to 5.29.0 release), we can ship upgrades to infra config, security, policies, new functionality, etc., without you having to do a single thing: because Pulumi is code, and it comes from our NPM packages.

Having said all that, I highly doubt that we'll be investing any effort into making Webiny deployable using any other tools, because that would directly affect the maintainability of the system, and add unnecessary complexity to everything we build, because all of a sudden we have to make it work with more than 1 tool.
