### ISSUE TITLE
dependencies failing

### ISSUE THREAD

**Issue by tylercowie** [webiny/webiny-js#2880]
### What are the steps to reproduce this bug?

root@webiny-ubuntu:/webiny# npx create-webiny-project webiny-narrowstackInitializing a new Webiny project in /webiny/webiny-narrowstack...
  ✔ Prepare project folder
  ✔ Setup yarn
  ✔ Install template package
  ✔ Initialize git
Starting @webiny/cwp-template-aws template ...

In order to setup your new Webiny project, please answer the following questions.

? Please choose the AWS region in which your new project will be deployed: us-east
-2 (US East, Ohio)
? Please choose the database you wish to use with your Webiny project: DynamoDB (f
or small and medium sized projects)
⏳ Installing dependencies....

➤ YN0000: ┌ Resolution step
➤ YN0061: │ eslint-plugin-standard@npm:5.0.0 is deprecated: standard 16.0.0 and eslint-config-standard 16.0.0 no longer require the eslint-plugin-standard package. You can remove it from your dependencies with 'npm rm eslint-plugin-standard'. More info here: https://github.com/standard/standard/issues/1316
➤ YN0000: ⠋ @babel/plugin-bugfix-safari-id-destructuring-collision-in-function-exp
➤ YN0061: │ i18n-locales@npm:0.0.2 is deprecated: Please upgrade to v0.0.3+ as we have fixed missing ISO-639-1 codes
➤ YN0061: │ @fortawesome/fontawesome-svg-core@npm:1.3.0 is deprecated: Please upgrade to 6.1.0. https://fontawesome.com/docs/changelog/
➤ YN0061: │ @fortawesome/fontawesome-common-types@npm:0.3.0 is deprecated: Please upgrade to 6.1.0. https://fontawesome.com/docs/changelog/
➤ YN0061: │ react-native-web@npm:0.12.3 is deprecated: < 0.16.0 is no longer supported
➤ YN0061: │ react-images@npm:0.5.19 is deprecated: This beta version is no longer supported. Please update to 1.1.0-beta.4
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ @aws-sdk/util-base64-browser@npm:3.109.0 is deprecated: The package @aws-sdk/util-base64-browser has been renamed to @aws-sdk/util-base64. Please install the renamed package.
➤ YN0061: │ @aws-sdk/util-base64-node@npm:3.55.0 is deprecated: The package @aws-sdk/util-base64-node has been renamed to @aws-sdk/util-base64. Please install the renamed package.
➤ YN0061: │ left-pad@npm:1.3.0 is deprecated: use String.prototype.padStart()
➤ YN0061: │ deep-assign@npm:3.0.0 is deprecated: Check out `lodash.merge` or `merge-options` instead.
➤ YN0061: │ core-js@npm:2.6.12 is deprecated: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
➤ YN0061: │ @types/classnames@npm:2.3.1 is deprecated: This is a stub types definition. classnames provides its own type definitions, so you do not need this installed.
➤ YN0061: │ @babel/polyfill@npm:7.12.1 is deprecated: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
➤ YN0061: │ stable@npm:0.1.8 is deprecated: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
➤ YN0061: │ @npmcli/move-file@npm:2.0.1 is deprecated: This functionality has been moved to @npmcli/fs
➤ YN0000: ⠏ @babel/template@npm:^7.3.3

ERROR OUTPUT: 
----------------------------------------
Failed while installing project dependencies. Please check the above logs for more information.

SYSTEM INFORMATION: 
----------------------------------------
Operating System: linux
Node: 18.7.0
Yarn: 3.3.0
create-webiny-project: 5.33.4
Template: N/A
Template Options: {}

Please open an issue including the error output at https://github.com/webiny/webiny-js/issues/new.
You can also get in touch with us on our Slack Community: https://www.webiny.com/slack

Writing log to /webiny/cwp-logs.txt...
Cleaning up generated files and folders...
Done.

**Comment by brunozoric** [comment]
Hi @tylercowie 
Do you mind trying to install with Node v14 or v16?

**Comment by mmunem** [comment]
Hi @brunozoric, I tried it just now. Tried with both v14 and v16
**v16 log here**

`DCEPrincipal-dce:~/environment $ npx create-webiny-project webiniy-demo
Initializing a new Webiny project in /home/ec2-user/environment/webiniy-demo...
  ✔ Prepare project folder
  ✔ Setup yarn
  ✔ Install template package
  ✔ Initialize git
Starting @webiny/cwp-template-aws template ...

In order to setup your new Webiny project, please answer the following questions.

? Please choose the AWS region in which your new project will be deployed: us-east-1 (US East, N. Virginia)
? Please choose the database you wish to use with your Webiny project: DynamoDB (for small and medium sized projects)
⏳ Installing dependencies....

➤ YN0065: Yarn will periodically gather anonymous telemetry: https://yarnpkg.com/advanced/telemetry
➤ YN0065: Run yarn config set --home enableTelemetry 0 to disable

➤ YN0000: ┌ Resolution step
➤ YN0061: │ eslint-plugin-standard@npm:5.0.0 is deprecated: standard 16.0.0 and eslint-config-standard 16.0.0 no longer require the eslint-plugin-standard package. You can remove it from your dependencies with 'npm rm eslint-plugin-standard'. More info here: https://github.com/standard/standard/issues/1316
➤ YN0061: │ i18n-locales@npm:0.0.2 is deprecated: Please upgrade to v0.0.3+ as we have fixed missing ISO-639-1 codes
➤ YN0061: │ @fortawesome/fontawesome-svg-core@npm:1.3.0 is deprecated: Please upgrade to 6.1.0. https://fontawesome.com/docs/changelog/
➤ YN0061: │ @fortawesome/fontawesome-common-types@npm:0.3.0 is deprecated: Please upgrade to 6.1.0. https://fontawesome.com/docs/changelog/
➤ YN0061: │ react-images@npm:0.5.19 is deprecated: This beta version is no longer supported. Please update to 1.1.0-beta.4
➤ YN0061: │ react-native-web@npm:0.12.3 is deprecated: < 0.16.0 is no longer supported
➤ YN0061: │ @aws-sdk/util-base64-node@npm:3.186.0 is deprecated: The package @aws-sdk/util-base64-node has been renamed to @aws-sdk/util-base64. Please install the renamed package.
➤ YN0061: │ left-pad@npm:1.3.0 is deprecated: use String.prototype.padStart()
➤ YN0061: │ @aws-sdk/util-base64-browser@npm:3.186.0 is deprecated: The package @aws-sdk/util-base64-browser has been renamed to @aws-sdk/util-base64. Please install the renamed package.
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ deep-assign@npm:3.0.0 is deprecated: Check out `lodash.merge` or `merge-options` instead.
➤ YN0061: │ @types/classnames@npm:2.3.1 is deprecated: This is a stub types definition. classnames provides its own type definitions, so you do not need this installed.
➤ YN0061: │ core-js@npm:2.6.12 is deprecated: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
➤ YN0061: │ @babel/polyfill@npm:7.12.1 is deprecated: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
➤ YN0061: │ stable@npm:0.1.8 is deprecated: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
➤ YN0061: │ @npmcli/move-file@npm:2.0.1 is deprecated: This functionality has been moved to @npmcli/fs
➤ YN0061: │ @aws-sdk/util-base64-browser@npm:3.6.1 is deprecated: The package @aws-sdk/util-base64-browser has been renamed to @aws-sdk/util-base64. Please install the renamed package.
➤ YN0061: │ @aws-sdk/util-base64-node@npm:3.6.1 is deprecated: The package @aws-sdk/util-base64-node has been renamed to @aws-sdk/util-base64. Please install the renamed package.
➤ YN0061: │ uuid@npm:3.4.0 is deprecated: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
➤ YN0000: ⠇ @material/progress-indicator@npm:^5.1.0`


ERROR OUTPUT: 
----------------------------------------
Failed while installing project dependencies. Please check the above logs for more information.

SYSTEM INFORMATION: 
----------------------------------------
Operating System: linux
Node: 16.19.0
Yarn: 3.3.1
create-webiny-project: 5.34.0
Template: N/A
Template Options: {}

Please open an issue including the error output at https://github.com/webiny/webiny-js/issues/new.
You can also get in touch with us on our Slack Community: https://www.webiny.com/slack

**Comment by brunozoric** [comment]
hi @mmunem 
I don't see any error in the output.
Is there a cwp-logs.txt in the directory where you started the `npx create-webiny-project`?

**Comment by mmunem** [comment]
@brunozoric - thanks for looking into this. Not much info. there i.e. 

DCEPrincipal-dce:~/environment $ cat cwp-logs.txt 
Error: Failed while installing project dependencies. Please check the above logs for more information.


I can only assume that "above" means the output below:

`DCEPrincipal-dce:~/environment $ npx create-webiny-project webiniy-demo
Initializing a new Webiny project in /home/ec2-user/environment/webiniy-demo...
  ✔ Prepare project folder
  ✔ Setup yarn
  ✔ Install template package
  ✔ Initialize git
Starting @webiny/cwp-template-aws template ...

In order to setup your new Webiny project, please answer the following questions.

? Please choose the AWS region in which your new project will be deployed: us-east-1 (US East, N. Virginia)
? Please choose the database you wish to use with your Webiny project: DynamoDB (for small and medium sized projects)
⏳ Installing dependencies....

➤ YN0065: Yarn will periodically gather anonymous telemetry: https://yarnpkg.com/advanced/telemetry
➤ YN0065: Run yarn config set --home enableTelemetry 0 to disable

➤ YN0000: ┌ Resolution step
➤ YN0061: │ eslint-plugin-standard@npm:5.0.0 is deprecated: standard 16.0.0 and eslint-config-standard 16.0.0 no longer require the eslint-plugin-standard package. You can remove it from your dependencies with 'npm rm eslint-plugin-standard'. More info here: https://github.com/standard/standard/issues/1316
➤ YN0061: │ i18n-locales@npm:0.0.2 is deprecated: Please upgrade to v0.0.3+ as we have fixed missing ISO-639-1 codes
➤ YN0061: │ @fortawesome/fontawesome-svg-core@npm:1.3.0 is deprecated: Please upgrade to 6.1.0. https://fontawesome.com/docs/changelog/
➤ YN0061: │ @fortawesome/fontawesome-common-types@npm:0.3.0 is deprecated: Please upgrade to 6.1.0. https://fontawesome.com/docs/changelog/
➤ YN0061: │ react-images@npm:0.5.19 is deprecated: This beta version is no longer supported. Please update to 1.1.0-beta.4
➤ YN0061: │ react-native-web@npm:0.12.3 is deprecated: < 0.16.0 is no longer supported
➤ YN0061: │ @aws-sdk/util-base64-node@npm:3.186.0 is deprecated: The package @aws-sdk/util-base64-node has been renamed to @aws-sdk/util-base64. Please install the renamed package.
➤ YN0061: │ left-pad@npm:1.3.0 is deprecated: use String.prototype.padStart()
➤ YN0061: │ @aws-sdk/util-base64-browser@npm:3.186.0 is deprecated: The package @aws-sdk/util-base64-browser has been renamed to @aws-sdk/util-base64. Please install the renamed package.
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ deep-assign@npm:3.0.0 is deprecated: Check out `lodash.merge` or `merge-options` instead.
➤ YN0061: │ @types/classnames@npm:2.3.1 is deprecated: This is a stub types definition. classnames provides its own type definitions, so you do not need this installed.
➤ YN0061: │ core-js@npm:2.6.12 is deprecated: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
➤ YN0061: │ @babel/polyfill@npm:7.12.1 is deprecated: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
➤ YN0061: │ stable@npm:0.1.8 is deprecated: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
➤ YN0061: │ @npmcli/move-file@npm:2.0.1 is deprecated: This functionality has been moved to @npmcli/fs
➤ YN0061: │ @aws-sdk/util-base64-browser@npm:3.6.1 is deprecated: The package @aws-sdk/util-base64-browser has been renamed to @aws-sdk/util-base64. Please install the renamed package.
➤ YN0061: │ @aws-sdk/util-base64-node@npm:3.6.1 is deprecated: The package @aws-sdk/util-base64-node has been renamed to @aws-sdk/util-base64. Please install the renamed package.
➤ YN0061: │ uuid@npm:3.4.0 is deprecated: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
➤ YN0000: ⠇ @material/progress-indicator@npm:^5.1.0`

`ERROR OUTPUT:
----------------------------------------
Failed while installing project dependencies. Please check the above logs for more information.

SYSTEM INFORMATION:
----------------------------------------
Operating System: linux
Node: 16.19.0
Yarn: 3.3.1
create-webiny-project: 5.34.0
Template: N/A
Template Options: {}

Please open an issue including the error output at https://github.com/webiny/webiny-js/issues/new.
You can also get in touch with us on our Slack Community: https://www.webiny.com/slack

Writing log to /home/ec2-user/environment/cwp-logs.txt...
Cleaning up generated files and folders...
Done.`

**Comment by mmunem** [comment]
Update to the above. It worked fine with same versions of node/yarn on my macbook. The error above must be somehow related to AWS Cloud9 weirdness.

**Comment by brunozoric** [comment]
Hi @mmunem 
Probably yes. We haven't tested it like that. Maybe not enough memory?
Sorry for slow response.

I will close the issue.
