### ISSUE TITLE
Waitlist form does not work! Also all forms built on page builder.

### ISSUE THREAD

**Issue by joeygeo** [webiny/webiny-js#2913]
### What are the steps to reproduce this bug?

Could not find any other way to convey this message, so adding it as a github bug!
This business plan waitlist form has stopped working - https://site.webiny.com/forms/business-waiting-list

It fails with a CORS error. It looks like a generic problem with all forms created in page builder.

### What is the expected behavior?

Form should submit successfully.

### What do you see instead?

CORS error in browser console, and page is stuck.

### Additional information

https://i.imgur.com/OQLLdtK.jpeg

### Possible solution

fix CORS headers on web-server/cdn config.

**Comment by SvenAlHamad** [comment]
@joeygeo - thanks for letting us know about the issue. Can you confirm which browser and version you are using? 
We've tried the form and it's working fine for us, and we've also received a few submissions to the form in the mean time, telling us it's working for other users.

**Comment by joeygeo** [comment]
I am using Chrome - latest version.
Tried now on MS Edge - same error.
Also tested on Android Chrome browser... form will not submit.

**Comment by joeygeo** [comment]
The error is from ipify.org - is that something you are using?

**Comment by SvenAlHamad** [comment]
Found the issue. I've logged the details here #2915. We'll address this soon.

**Comment by joeygeo** [comment]
I see incident is closed, but business plan waiting list form is still not working...
When will the fix be deployed to site.webiny.com?
I have tried so many browsers, is there a workaround until then?

**Comment by SvenAlHamad** [comment]
Hey @joeygeo - just confirming the issue is fixed.
The issue was only happening when you have specific ad blockers installed in your browser. 

You can now submit the business waiting list form. The next Webiny release will have this patch included so when you update your instance your form builder will work fine. For time being you can just disable your ab blocker and it will work fine.

**Comment by joeygeo** [comment]
I don't have any ad blockers. Irrespective, I have already tried the form in Firefox, Chrome, edge, soul browsers. I also tried inprivate/incognito mode, all lead to same error.

**Comment by joeygeo** [comment]
I don't think its a browser issue. Your server/cdn config is not handling CORS headers correctly.

**Comment by SvenAlHamad** [comment]
The CORS error tends to be misleading. Because we return the CORS headers directly from our lambda function, if there's an error in the Lambda function, the headers don't get attached, and the browser then complains about the CORS missing, but the actual error is something else. 

If you do another test and check your console, let me know if you see any errors. 

Btw, we did get your application now and can see it in our system.
