### ISSUE TITLE
Background image - scaling select not working

### ISSUE THREAD

**Issue by SvenAlHamad** [Webiny/webiny-js#321]
In one of my previous commits, I had to change the select options from the options html tag, to options as a prop. 

**See commit:** 
https://github.com/Webiny/webiny-js/pull/319/commits/5feb85963b18e04d26cb87d961da0ad7800f6015#diff-49b07bf36b2b9b852a768e0232c48f6f
**Lines**: 163 - 177

The same type of a select works fine on other components, but not here. Please check it out.

**Comment by adrian1358** [comment]
@SvenAlHamad Here it does not work because on the top of the file, Select is imported from `import Select from "webiny-app-cms/editor/plugins/elementSettings/components/Select";`. This component does not accept children.

But it seems there is an issue with onChange callback, so I will take a look at that here.

**Comment by adrian1358** [comment]
This is fixed. The issue was only in passed props that were sent to the Select component. 

Note that this Select is not the one from `webiny-ui`, but from `webiny-app-cms`, which is specially optimized for editor.

@SvenAlHamad
