### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by theluk** [webiny/webiny-js#565]
## Question

Hey guys,

great work, what you have built until now looks great. 

We are thinking about if it is possible to use some core features of webiny in a existing system, where we want to slowly transition from. 

Now we saw that you guys are heavily working in the development branch, where we see a ton of changes. What we now are questioning, what if we just jump into the master, going all in, writing our plugins, custom integrations in the apis, start loving it etc etc etc, and then you release something completely breaking where we will not be able to transition to and potentially stay at an older version. On the other hand there are so many commits in development that it almost seem as there might never happen a full merge back into master... So we also thought about just jumping into the development branch, even though not ready. What I would love to hear is a little bit of a short info about the plans or current state.

**Comment by Pavel910** [comment]
Hi @theluk, thanks for reaching out!

There are so many commits in the development branch because we're closing in on our next big release. We'll be releasing our entire platform 100% open-source and self-hostable on AWS, with multi-cloud support later on. Everything powered by Serverless Framework, or better to say, the  [Components](https://github.com/serverless/components) part of it.

There were some important developments during summer that changed the course of our entire product and a big announcement is about to be made, all in the upcoming weeks. So please stay tuned and subscribe to our newsletter to be notified :)

As to your concern regarding breaking changes, once this release is out we're not going to do any major architectural changes for at least a year. We'll only be adding features and fixes on top of the platform (and of course tons of tutorials and documentation). Even if we do release a breaking change, it will not be due to a complete system overhaul, but rather to stay updated with the dependencies we use (3rd party packages), just so we don't get entirely obsolete. But there will always be a clear migration guide and even codemods where possible.

We are concerned with major changes just as much as you are, and we'll do our best to keep them under control :)

If you have more questions, please do send them our way!
Cheers! 🍻
