### ISSUE TITLE
API - Improve error reporting

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#577]
## This is:
- Bug

## Specifications
Not important.

## Expected Behavior
Show what's wrong, at least while the developer is in process of developing his / her app.

## Actual Behavior
The following screenshot shows the response that's returned when something is wrong on the backend.
![image](https://user-images.githubusercontent.com/5121148/67886969-b7202680-fb4a-11e9-95e9-62511d610425.png)

## Steps to Reproduce the Problem
N/A

## Detailed Description
The main problem with this is that the error could come from any of the federated GraphQL services. Even in the initial setup, there are already 8 Lambda functions, which makes it very hard for the developer to do debugging. The only thing he can do to check the CloudWatch of each Lambda function, which is a pretty bad DX.

## Possible Solution
TBD

**Comment by Pavel910** [comment]
This problem is a big one, because there is no such thing as `development` for API Gateway.
I think this is something a developer needs to be able to control via ENV variable, which will tell API Gateway to show the errors from lambdas. So when a variable `API_GW_SHOW_ERRORS` (for example) is `true` - the deploy process would enable error forwarding (if it is at all possible, need to research).

**Comment by doitadrian** [comment]
@SvenAlHamad mentioned we might also return the ID of the Lambda, so users can easier go to CloudWatch and find the Lambda that's causing issues.

Might not be relevant when we start working on this, but still wanted to note it here, maybe it'll be helpful.

**Comment by Pavel910** [comment]
This one is solved and released.
