### ISSUE TITLE
Delete of images is not working

### ISSUE THREAD

**Issue by mectors** [webiny/webiny-js#637]
## This is:

- Bug

## Specifications

  - version: 2.4.1
  - OS: Mac and AWS
  - Browser: Chrome

## Expected Behavior

Clicking the delete image button should delete the image 

## Actual Behavior

Nothing happens

## Steps to Reproduce the Problem

1. Open page builder
2. Add image element
3. Upload image
4. Click the i on the image
5. Click the Delete Image icon

## Detailed Description

After clicking delete image the image should be removed.

**Comment by Pavel910** [comment]
Thanks @mectors, we'll look into it.

**Comment by mectors** [comment]
thanks

**Comment by doitadrian** [comment]
I just tried deleting an existing image, it worked for me.

Can you please check if there is an error in the console? 

Let me know if you need any help with that.

**Comment by doitadrian** [comment]
Hey @mectors, I actually followed exact same steps you provided.

And I managed to reproduce it.

I click on the garbage can icon, and really, nothing gets triggered.

Thanks a lot for the report, will check this out!

**Comment by doitadrian** [comment]
Hi @mectors,

this has been fixed and released. The issue was happening only inside of the Page Builder. In other places, like for example account settings (where you can upload your avatar image), this worked correctly. 

Somehow we missed the issue you found in the Page Builder, but it is fixed (and released) now.

To get the fix, just upgrade the `@webiny/app-admin` package, by doing `yarn upgrade @webiny/app-admin` in the root of your Webiny installation. This should pull the newest `2.1.2` version.
