### ISSUE TITLE
Deploy button and/or docker-compose

### ISSUE THREAD

**Issue by jozef-slezak** [webiny/webiny-js#650]
Hello, great job done with Webiny! You can inspire by "Deploy to Cloud" button. Deploy button is being used in many opensource projects (eg. https://github.com/parse-community/parse-server-example). I understand the benefits of serverless but it complicates quickstart (I beleive that it simplifies production deployment). Please consider:
A. simple deployment to a cloud simmilar to https://docs.hasura.io/1.0/graphql/manual/getting-started/heroku-simple.html
B. simple localhost environment simmilar to https://docs.hasura.io/1.0/graphql/manual/getting-started/docker-simple.html

I have been playing with Webiny for two days and found few hurdles:
1. Quickstart me for Cognito configuration https://docs.webiny.com/docs/get-started/quick-start
2. Docker compose not worked for me https://community.webiny.com/t/developer-docker-skeleton-to-launch-webiny-in-local-with-docker/58
3. https://github.com/webpack-contrib/sass-loader/issues/756
4. `webiny deploy-apps` requires environment (but the instructions https://www.webiny.com/ not; please consider also extending the description in https://docs.webiny.com/docs/get-started/going-live#!)
5. then I started local admin app using `yarn start` but received error message `Access to fetch at 'https://d1r8vb5x846aw.cloudfront.net/graphql' from origin 'http://localhost:3001' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

## This is:
- Feature request

**Comment by Pavel910** [comment]
Hi @jozef-slezak, thanks for giving Webiny a spin :)

1. Not sure what was the problem here, as you **don't** need to do anything with Cognito, it is set up during the initial deploy of your API. Could you provide some details?

2. That docker image is created by a community member for Webiny `v1`, not the serverless `v2`.

3. The `sassOptions` was fixed about 2 weeks ago, so all new projects (since the fix) contain the correct configuration.

4. The article does contain the `--env=dev` flag, anything specific you'd like us to add ?

5. This can happen for 2 reasons: 
1) the CDN is still not accessible (this is normal for 5-7 minutes after initial deploy)
2) there may be errors on the API that prevent it from sending any response at all.
This unfortunately requires some debugging.

As for docker and heroku: our focus on serverless is intentional, and we do not plan on adding any kind of container deployment support. I had a long debate regarding this in [this issue](https://github.com/webiny/webiny-js/issues/570) so please do take a look at it to better understand our position.

Please let us know if we can be of more help, and definitely send us ideas on how we can improve our docs. Cheers!

**Comment by doughnet** [comment]
agree this would be good.

i was going to try out webinly CMS but after the complexity of setting it up I'm staying away until a proper installation is provided.

**Comment by Pavel910** [comment]
@doughnet Would you care to clarify which part of the setup you find complex? Thanks!

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
