### ISSUE TITLE
Broken link in `examples/apps/admin/README.md`

### ISSUE THREAD

**Issue by jbampton** [webiny/webiny-js#656]
The `Post-Processing CSS` link in the table of contents is broken.  The markup that it links to is malformed and seems to be commented out. 

https://github.com/webiny/webiny-js/blob/master/examples/apps/admin/README.md

## This is:
- Bug

![Screen Shot 2020-01-07 at 5 35 37 am](https://user-images.githubusercontent.com/418747/71843718-3b28f880-3110-11ea-917c-2bd4e87812f4.png)

![Screen Shot 2020-01-07 at 5 36 19 am](https://user-images.githubusercontent.com/418747/71843737-454af700-3110-11ea-9341-cfa013bc10cf.png)

**Comment by Pavel910** [comment]
That README is from CRA setup, and is not really relevant, as the entire `examples` folder is just a sandbox to use while developing. It was created ages ago, and I believe it's been fixed in `create-react-app`  since then. 

Thanks for pointing out, I'll see if it's best to delete that file entirely to avoid confusion in the future.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
