### ISSUE TITLE
Quick start page is broken

### ISSUE THREAD

**Issue by zhex900** [webiny/webiny-js#675]
Hi,

Your project sounds very interesting. However, the quick start page is broken. 

Jake

**Comment by Pavel910** [comment]
Hey @zhex900, thanks for reporting, something must have gone wrong with the last deploy. However, if you open the [link directly](https://docs.webiny.com/docs/get-started/quick-start/), the page does load. Something is wrong with page transitions, will check.

Cheers 🍻

**Comment by zhex900** [comment]
Great! Thank you. I thinking about contributing to this project. Where will
be a good starting point?

**Comment by Pavel910** [comment]
Awesome! For new contributors, there are [issues labeled `good-first-issue`](https://github.com/webiny/webiny-js/issues?q=is%3Aopen+is%3Aissue+label%3Agood-first-issue). Those are easy ones, and will help you to get to know the project.

However, my recommendation is to wait for our next release (1-2 days at most), since we've migrated the whole project to TypeScript, and we still have to merge it into the `master` branch.

Also, feel free to join our chat at https://gitter.im/Webiny/webiny-js if you need any help; we're online most of the day.

I'll let you know when the repo is ready for forking and contributions!

**Comment by Pavel910** [comment]
@zhex900 we released the new version of Webiny; if you're working on a fork of our repo, update your fork. Everything is in the `master` branch. Let me know if you need help with anything :)

**Comment by Pavel910** [comment]
Thanks to @doitadrian, docs are now fixed; closing this issue.
