### ISSUE TITLE
Admin - implement better auth error handling

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#712]
## This is:

- Bug

## Actual Behavior
When opening admin with an old (from previous installation) or invalid token, users get the following error:

![image](https://user-images.githubusercontent.com/5121148/74251177-064e2980-4cec-11ea-8a36-6aeee22ff792.png)

## Expected Behavior
We should implement better error handling.

**Comment by Juan007** [comment]
Hi, I've just installed Webiny and I am receiving this error. What exactly needs to be done to resolve the issue from my side?

**Comment by doitadrian** [comment]
Thanks for the question @Juan007.


@Pavel910 If you want I can check the exact steps/implementation details and outline them here.

**Comment by Juan007** [comment]
I'm sure I simply botched something small during initial setup!

I'm going to make some assumptions here: 
I'm busy with the setup process where I'm supposed to launch the admin portion and run through the setup wizard for the first time.

When I load the page (http://localhost:3001/admin), it shows the following briefly before redirecting:
![image](https://user-images.githubusercontent.com/2021922/76604010-9dd6b000-6516-11ea-9517-1499d4ac6277.png)

It then redirects to http://localhost:3001/admin/page-builder/pages, which I'm assuming is not available yet because I have not completed the setup wizard.

**Comment by Pavel910** [comment]
Hey @Juan007, could you verify your API is actually working? Simply open you API URL and if everything is ok, it should load the GraphQL Playground. If not, you'll get some insight into errors under the hood.

Sorry you ran into problems. We're here to help resolve this so feel free to post every bit of information you have. Cheers!

**Comment by Juan007** [comment]
Thanks, also - I raised this issue on the wrong page! Apologies, I misread the error in your screenshot. 

Here's the error I am receiving:
![image](https://user-images.githubusercontent.com/2021922/76604529-88ae5100-6517-11ea-88d6-adad1e2a68d8.png)
 
I've deleted the project and restarted (just in case I've missed a step).

I'm following this tutorial: https://docs.webiny.com/docs/get-started/quick-start

Not sure if I missed this error before, but when I run `webiny deploy-api`, it throws the following error:
![image](https://user-images.githubusercontent.com/2021922/76607085-083e1f00-651c-11ea-91ff-f44c5456ca45.png)

So clearly the issue was indeed that the API is not running.

**Comment by doitadrian** [comment]
This is a different error message, so a new #753 issue was created.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
