### ISSUE TITLE
Headless CMS

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#749]
This issues contains the list of tasks that need to be completed before launching Headless CMS:

## API
- [x] Allow creation of content models without fields (add tests)
- ~Create `@webiny/serverless-cms` component which will deploy a separate Apollo GW + Headless service and expose 3 endpoints `/cms/read`, `/cms/manage`, `/cms/preview`, + `{env}` combinations. These endpoints all route to the same apollo-gw, which then loads schema based on `env`~
- [x] Add support for content revisions
- [x] Add support for multiple environments (`default` environment is created via installer, users can create their own environments and select which one is `default`, to promote custom environments to be the main source of content)
- [x] Reload GQL schema when content model is published (Apollo Gateway + Headless service)
- [x] CMS schema should be generated in the root of the schema. 
- ~`security` and `files` should be resolved using `graphql` query to the original service, to avoid schema cluttering and duplicate service entry points: `packages/api-i18n/src/plugins/service.ts:43`~
- [ ] Generate security scopes for each content model
- [x] Enable users to create "List" fields. These are just like regular fields, except here, users can enter multiple values. For example, if this feature was enabled on a text field, users would be able to enter multiple text values in the actual form.
- ~add `isSearchable` property to `CmsModelFieldToGraphQLPlugin`~

## Admin app
- [x] Create `Content Model` editor
- [x] Dynamically generate CRUD modules (with menus) for content models
- [x] Add a module to control menus for content models (each model must be assigned into a specific menu)
- [x] Create an installer which does the following:
  - creates a default menu for all content 
  - creates a default environment
- [ ] add `isSortable` and `isSearchable` to field types in Content Model

## Other
- [x] eliminate step 6 in the Page Builder installation (`packages/api-page-builder/src/plugins/graphql/installResolver/install.ts:131`). Not needed since the new version be a major one.

## Docs
- [ ] in [Rendering Pages](http://localhost:3000/docs/webiny-apps/page-builder/development/rendering-pages/#manually-passing-the-page-data) article, we'll need to change the part about importing page-element-rendering plugins.
- [ ] [Registering a theme](https://docs.webiny.com/docs/webiny-apps/page-builder/theme-development/basic-concepts#registering-a-theme) - uses old paths

## Site updates
- [x] remove `serverless framework`
- [x] update webiny CLI usage example on homepage

**Comment by doitadrian** [comment]
### Handling locales with localized / non-localized fields

Had a discussion with @Pavel910 today, and we agreed on the following.

1. Fields can be localized (contain values for multiple languages) and non-localized. This was already established before, and we again confirmed that it is the way to go.

2. On the GraphQL interface level, on the Manage API, a single content model field (e.g. text, integer, float, ...) can be represented in two ways:

2.1. For non-localized, we use just simple scalar types and inputs whenever possible. For example, for the text field, both for input and type, we will use `String` type.

2.2. For localized fields, just like we already do, we use I18N-based input and type. So, for the same text field we had in 2.1., this time we would use the following `CmsTextInput` and `CmsTextInput`:

![image](https://user-images.githubusercontent.com/5121148/79233714-836f5980-7e69-11ea-9eba-7d5ca675aaa0.png)

![image](https://user-images.githubusercontent.com/5121148/79233593-6175d700-7e69-11ea-8153-899ea134385e.png)

The motivation for this came from the fact that the user would have to copy values to all locales when dealing with the non-localized field. This way, he would only submit a single value, and the backend would do the rest.

Note that in spite of us changing the GraphQL interface, the data in the database will still be structured in the same way we have for localized fields. Meaning, we will just assign the same value for every available locale. But again, this happens in the backend, it's really something user won't have to think about.

3. Updates on the Search table will happen every time a content model is updated, for now synchronously. 

3.1. For localized fields, for each available locale, we create one entry in the Search table.

3.2. For non-localized fields, again, again, for each available locale, we create one entry in the Search table. Note that here we store the same value for every locale. This basically makes per-locale search queries easier / more performant and makes the code more straight-forward.

4. Moving on, we thought about what's happening in the system when user is doing changes on locales in the I18N module.

4.1. If a user is not removing/adding locales, just switching the default one, we don't have any issues, both for localized and non-localized fields.

4.2. In the following points, we examine what happens on adding and removing locales.

4.2.1. When adding a locale, everything is solid for localized fields. Simply, when opening existing content model entries in the admin, the values for the new locale will be empty, which is to be expected/is reasonable. The search will also work as expected. More specifically, it will not work, because values are not existing for the new locale.

4.2.2. When adding a locale, for non-localized fields, the situation gets a bit tricky. Since we agreed that for these fields, we just store the same value for every locale, both in the actual content model entry (non-searchable) and in the Search table, all of the entries with at least one non-localized field will have missing data - every non-localized field won't have the value for newly added locale. For example:

```js
{
  color: [
    { locale: "existing-locale-1", value: "the-same-value-for-every-locale" },
    { locale: "existing-locale-2", value: "the-same-value-for-every-locale" }
    // { locale: "newly-added-locale", value: "the-same-value-for-every-locale" } // Doesn't exist.
  ]
}
```

An even better example with `sku` field, which is a typical non-localized field:

```js
{
  sku: [
    { locale: "existing-locale-1", value: "SHOE-SMALL-RED" },
    { locale: "existing-locale-2", value: "SHOE-SMALL-RED" }
    // { locale: "newly-added-locale", value: "SHOE-SMALL-RED" } // Doesn't exist.
  ]
}
```

So, the value for `newly-added-locale` doesn't exist in the database, both in the content model entry and in the Search table. Content model entry is not problematic really, more problematic is the Search table, because if a user has the newly added locale selected, and does a search, he wouldn't get any results, because the Search catalog wasn't updated. So, based on the SKU example, if doing a search with a SKU, the search would not return anything, even though it should.

##### When will the missing data be populated and when is this problematic state of data resolved?

The data for the new locale is going to be populated only when the user actually does a save on the entry in the admin. Then, the system would, as usual, assign the same value for all locales, and update the Search table.

The alternative is to, upon adding a new locale, run an async job that would populate the missing values. So, in this process, we would iterate over all content model entries (for all environments) and just add the missing value. Once saved, this would also automatically update the Search table entries.

We figured that for v1, we won't be implementing like this.

4.2.3. What if the user marks the newly added locale as default one?
Well, when opening a specific entry, he would get empty data, because the admin didn't enter the new values for the newly created locale. The search also won't work until the user enters the missing data.

4.3. In **4.2** points, we discussed what's happening on adding a locale, but what is happening on removal? For both localized and non-localized fields, we have a problem of the data still existing for the just-deleted locale. But this is not really an issue since the API only allows accessing the database with existing locales. Additionally, as the entries are saved via the Admin, redundant data will be cleaned automatically.

The only thing I would add here is the deletion of entries in the Search table. So, we should just find all of the entries that are related to the just-deleted locale and delete them.

**Comment by SvenAlHamad** [comment]
What if we take the approach that all fields must be localized? The only downside here is that the user will need to copy/paste some field value across multiple languages. Which I agree is a bit on a pain, but we can add some UX improvements in v2 to make this less of a problem, if users do actually complain. 

With this approach we remove the problem of adding a new locale.
Ideally we should try and support the following behaviors: 
1. When a user creates a new local, run a copy process in the background to copy the entries in the search table from the default locale to the new locale - this way the search works and the API as well. 

2. This approach also can be used to populate the missing data by copying the default local values in the content model to the new local. For this case we should also maybe examine how other systems are handling this at the moment. But ideally the values should be copied upon locale creation.

3. When deleting a locale, we should not rely on the fact that we can do a cleanup when a user edits a record. This would lead to a lot of garbage in the database. When a local is deleted we should run a process to clean the search table as well as the content model data.

This is just my view. I feel like relying on things happening in the Admin UI is not the best approach.

**Comment by doitadrian** [comment]
What do you think @Pavel910 about not having the localization as a field option?

I agree that we would avoid some tricky cases with this approach, and kinda feel this wouldn't be too much of a UX issue.

Regarding other points...

I think it all makes sense, we just thought to maybe leave the background processing to post-beta-launch. We'll see about it, it depends on the overall progress.

The only thing I'm not sure about is copying the default locale's value to the newly created locale value. For example, we've seen others just leaving the field empty, with no value at all.

**Comment by Pavel910** [comment]
@doitadrian @SvenAlHamad I'm ok with having all fields localizable, to handle the UX we can easily add `Copy values from ...` button to copy values from other locales into the locale you're editing.

I also agree that when you delete a locale, we should cleanup automatically, however this will require us to use some kind of event because i18n service is independent. Maybe we can add a simple plugin to `i18n` service (imported from `api-headless-cms`) which will trigger the cleanup lambda (to be discussed). 

What I don't agree with is copying of default data. Contentful doesn't copy anything. And I really don't see the point in copying. If you have EN, and you add a locale FR, what's the point of having english values, when they will never match the search for French word? Moreover, a user who will be doing French translations, will have to first delete the exiting English values before entering French values. So we actually give users more to do than if we just leave the locale values empty.
So I'm with Contentful on this. But if you have a good reason to copy - let's hear it.

**Comment by SvenAlHamad** [comment]
Cool, it seems you did your research ... I'm ok with not copying default local data in this case.
