### ISSUE TITLE
`webiny deploy-api` not working

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#753]
Continuing from #712...
---

Here's the error I am receiving:
![image](https://user-images.githubusercontent.com/2021922/76604529-88ae5100-6517-11ea-88d6-adad1e2a68d8.png)
 
I've deleted the project and restarted (just in case I've missed a step).

I'm following this tutorial: https://docs.webiny.com/docs/get-started/quick-start

Not sure if I missed this error before, but when I run `webiny deploy-api`, it throws the following error:
![image](https://user-images.githubusercontent.com/2021922/76607085-083e1f00-651c-11ea-91ff-f44c5456ca45.png)

So clearly the issue was indeed that the API is not running.

_Originally posted by @Juan007 in https://github.com/webiny/webiny-js/issues/712#issuecomment-598625506_

**Comment by doitadrian** [comment]
@Pavel910 @Juan007

I hope you don't mind, I moved this to a separate issue.

**Comment by Pavel910** [comment]
This error is actually not because of Webiny itself, but because when you run `webiny`, your terminal sees the `webiny.js` file and thinks you want to open that (see that `script` path in the dialog). 

My guess would be:
1) try removing `js` file association, so it doesn't attempt to open the file
2) try running this with `yarn webiny deploy-api --debug` (yarn will resolve to the appropriate binary file)
3) not sure if this is Git Bash or plain CMD; maybe try running this in Git Bash ?

Btw. I'm also using Windows, and it works fine, but I'm 100% sure I don't have that file association. We had this problem with another community member long ago, and he managed to narrow it down to file association.

In some future releases, I think we need to rename that `webiny.js` to `webiny.config.js` so this doesn't happen to people with `js` file association.

**Comment by Juan007** [comment]
Thanks! Hopefully this will help someone in future!

Yes, exactly that: So the issue was "windows by default associate `*.js` files with _Microsoft Windows Based Script Host_"
Issue explained and resolved here: https://stackoverflow.com/a/40864934

I'm attempting to deploy the API now, will revert back if my issue(s) has been resolved!

**Comment by Juan007** [comment]
Ok, so now I'm back to where I started.

Ran webiny `deploy-api`:
![image](https://user-images.githubusercontent.com/2021922/76609765-961c0900-6520-11ea-9c2a-30b20135b648.png)

Ran `yarn start` in `app/admin`:
![image](https://user-images.githubusercontent.com/2021922/76609863-b8158b80-6520-11ea-9038-e546641ef435.png)

Then when I browse, it's back to:
![image](https://user-images.githubusercontent.com/2021922/76609902-cebbe280-6520-11ea-90ff-e3dc26e6beac.png)

This happens both if I navigate to http://192.168.0.105:3001/admin or http://localhost:3001/admin

Where do I browse to access the API?

**Comment by Pavel910** [comment]
Try adding the `--debug` flag, so you actually see the output during deploy. So `webiny deploy-api --debug`. To me this looks like it failed all together, because normally you get output with your API URL, etc. Also, is this `cmd` or `git bash` ?

**Comment by Juan007** [comment]
Ok, will do. I'm running from `cmd`. Should I rather switch to `git bash`?

**Comment by Pavel910** [comment]
If you can, please do try `git bash` (that's what I'm using on Windows). `cmd` is really a horrible terminal :( Let me know how it goes :)

**Comment by Juan007** [comment]
Seems to be working. Is it normal to take quite a while?

![image](https://user-images.githubusercontent.com/2021922/76614441-c071c480-6528-11ea-8e5c-1dc7acb180f9.png)

**Comment by Pavel910** [comment]
Not this long... usually the first deploy takes about 3 minutes. 
Maybe try creating a blank new project with GitBash, and run a fresh deploy.

**Comment by Juan007** [comment]
Done! Finally! :)

**Learnings from this for users that might run into the same issues in the future:**

1. Make sure Windows associates `*.js` files as text editor (like Notepad or VS Code)
2. Run commands from Git Bash as administrator instead of using cmd
3. Be patient with the API deployment step. It takes a while. (mine took 429 seconds).
4. After API has been deployed, the output will will show you the API url that the application will use. Test that first. It can take up to 10 minutes to become available after first deploy.

**Comment by Pavel910** [comment]
Glad you made it! 👍
