### ISSUE TITLE
Webiny-app-form-builder with NextJS

### ISSUE THREAD

**Issue by dhavalsoni2001** [webiny/webiny-js#804]
## This is:

- Question

Can we use webiny-app-form-builder with NextJS?

**Comment by Pavel910** [comment]
Hi @dhavalsoni2001, all our apps are built using our system of plugins, and you can't just grab one app and use it as a standalone piece within another application. So short answer is `no`.

On our feature page for [Form Builder](https://www.webiny.com/serverless-app/form-builder) you can see how Form Builder is a part of a larger [app development framework](https://www.webiny.com/serverless-web-development-framework).

It all plays very nicely together, but you have to use the whole platform.

Thanks for looking into Webiny! Cheers 🍻

**Comment by doitadrian** [comment]
Hi @dhavalsoni2001, 

I would just add a short comment to this.

As @Pavel910 mentioned, currently, it's not possible. But, with a couple of tweaks / minor additions, the feature you're asking could become available (we already have the standalone [Form](https://docs.webiny.com/docs/webiny-apps/form-builder/react-component) component).

PRs are always welcome, so if you're up for it, we could give you some guidance in order to create the feature you're asking for. 

That being said, please have in mind that, even if you decide to do this, you would still need to deploy Webiny into AWS, because forms can be built only via the [form editor](https://docs.webiny.com/docs/webiny-apps/form-builder/introduction) and are served via GraphQL API, on which the mentioned `Form` component is relying on.

**Comment by dhavalsoni2001** [comment]
Hey, @doitadrian Definitely I would like to create PR for the same.  I am looking for your guidance on the same.

**Comment by doitadrian** [comment]
Hi @dhavalsoni2001,

thanks, will prepare a separate issue with some instructions for you, and then I'll notify you.

**Comment by dhavalsoni2001** [comment]
Hey, @doitadrian Thanks. I am looking forward to it.

**Comment by doitadrian** [comment]
Hi @dhavalsoni2001,

sorry for the delay, just swamped with all kinds of tasks.

Anyways, I create a sample code repo which shows how you can integrate Webiny Form Builder into a simple React app.

https://github.com/doitadrian/react-app-webiny-form-builder

This is the most basic form of how to do it, so before doing any changes on the actual Form Builder package, I wanted to hear your thoughts on it. I included some comments in there, just to help you out.

Anyways, when you get a chance, please take a look and let us know if that will work for you. If not, then we can switch to plan B - do the necessary code adjustments.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
